### ISSUE TITLE
Application build failure

### ISSUE THREAD

**Issue by nzhang-zh** [MatrixAI/TypeScript-Demo-Lib#15]
Running `nix-build release.nix -A application` in a freshly pulled repository failed. 

```
~/m/TypeScript-Demo-Lib ❯❯❯ nix-build release.nix -A application 
these derivations will be built:
  /nix/store/ah59sckpkf465lfqwvq7d870xqsyz7c7-node__at_matrixai_slash_typescript-demo-lib-0.0.2.drv
building '/nix/store/ah59sckpkf465lfqwvq7d870xqsyz7c7-node__at_matrixai_slash_typescript-demo-lib-0.0.2.drv'...
unpacking sources
patching sources
configuring
no configure script, doing nothing
building
installing
unpacking source archive /nix/store/42kp35fis2c30fl3i94azzihjjnhn7b0-TypeScript-Demo-Lib
pinpointing versions of dependencies...
patching script interpreter paths in .
./@matrixai/typescript-demo-lib/src/bin/typescript-demo-lib.ts: interpreter directive changed from "/usr/bin/env node" to "/nix/store/2w6ilfh7zmbz9zqvphgxinmbn3wdqa1b-nodejs-12.18.4/bin/node"
npm ERR! code ENOENT5minstall executeActions0mreeKK
npm ERR! syscall chmod
npm ERR! path /nix/store/899v9ab13hhck4359rsb3jymgp98hrak-node__at_matrixai_slash_typescript-demo-lib-0.0.2/lib/node_modules/@matrixai/typescript-demo-lib/dist/bin/typescript-demo-lib.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/nix/store/899v9ab13hhck4359rsb3jymgp98hrak-node__at_matrixai_slash_typescript-demo-lib-0.0.2/lib/node_modules/@matrixai/typescript-demo-lib/dist/bin/typescript-demo-lib.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2021-01-14T00_33_23_633Z-debug.log

builder for '/nix/store/ah59sckpkf465lfqwvq7d870xqsyz7c7-node__at_matrixai_slash_typescript-demo-lib-0.0.2.drv' failed with exit code 254
error: build of '/nix/store/ah59sckpkf465lfqwvq7d870xqsyz7c7-node__at_matrixai_slash_typescript-demo-lib-0.0.2.drv' failed
```

**Comment by nzhang-zh** [comment]
> npm ERR! path /nix/store/899v9ab13hhck4359rsb3jymgp98hrak-node__at_matrixai_slash_typescript-demo-lib-0.0.2/lib/node_modules/@matrixai/typescript-demo-lib/dist/bin/typescript-demo-lib.js

This seems similar failure while packaging `js-polykey` with nix. 

The solution was to prepare a `node_modules` directory in build phase. Will investigate further.

**Comment by nzhang-zh** [comment]
Some reference materials used before. 

- [Example from `node2nix`](https://github.com/svanderburg/node2nix#using-the-nodejs-environment-in-other-nix-derivations) readme for using node packages in nix.
  ```nix
  let
    nodeDependencies = (pkgs.callPackage ./default.nix {}).shell.nodeDependencies;
  in

  stdenv.mkDerivation {
    name = "my-webpack-app";
    src = ./my-app;
    buildInputs = [nodejs];
    buildPhase = ''
      ln -s ${nodeDependencies}/lib/node_modules ./node_modules
      export PATH="${nodeDependencies}/bin:$PATH"

      # Build the distribution bundle in "dist"
      webpack
      cp -r dist $out/
    '';
  }
  ``` 
- An existing js package in `nixpkgs`. https://github.com/NixOS/nixpkgs/pull/86169/commits/5e1cf2dbc31ad4fffa3e019b33f696da76eefcbe

**Comment by CMCDragonkai** [comment]
Literally node2nix is doing things incorrectly. I have a feeling we have to rewrite it a little bit.

On 14 January 2021 11:44:47 am AEDT, nzhang-zh <notifications@github.com> wrote:
>> npm ERR! path
>/nix/store/899v9ab13hhck4359rsb3jymgp98hrak-node__at_matrixai_slash_typescript-demo-lib-0.0.2/lib/node_modules/@matrixai/typescript-demo-lib/dist/bin/typescript-demo-lib.js
>
>This seems similar failure while packaging `js-polykey` with nix. 
>
>The solution was to prepare a `node_modules` directory in build phase.
>Will investigate further.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MatrixAI/TypeScript-Demo-Lib/issues/15#issuecomment-759849991

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by CMCDragonkai** [comment]
This is fixed?
